name: hab-sdk
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - requests
  - tqdm
  - xarray
  - netcdf4
  - cfgrib
  - eccodes
  - herbie-data
  - pyproj
  - rasterio
  - geopandas
  - contextily
  - cartopy
  - jupyterlab
  - ipykernel